# Generated by Django 5.1.4 on 2025-03-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand_catagory',
            name='slug',
        ),
    ]
