# Generated by Django 5.1.4 on 2025-03-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_remove_brand_catagory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_images',
            field=models.ImageField(default='images/im.jpeg', upload_to='cars_images/'),
        ),
    ]
