# Generated by Django 5.1.4 on 2025-03-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_car_car_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='car',
            name='qunity',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
