# Generated by Django 5.1.4 on 2025-03-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0005_car_description_car_qunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_catagory',
            name='slug',
            field=models.SlugField(default='null', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_images',
            field=models.ImageField(default='cars_images/im.jpeg', upload_to='cars_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='Nothing_details'),
        ),
        migrations.AlterField(
            model_name='car',
            name='qunity',
            field=models.IntegerField(default=0),
        ),
    ]
