# Generated by Django 5.1.4 on 2025-03-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0006_brand_catagory_slug_alter_car_car_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_catagory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
