# Generated by Django 5.1.4 on 2025-03-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0009_alter_brand_catagory_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand_catagory',
            name='slug',
        ),
    ]
